# Generated by Django 5.0.7 on 2025-03-07 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'Students'},
        ),
    ]
