# Generated by Django 5.0.7 on 2025-03-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_remove_subject_standard_subject_standard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='standard',
            new_name='standards',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
    ]
