# Generated by Django 5.0.7 on 2025-03-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_rename_standard_subject_standards_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='standards',
        ),
    ]
