# Generated by Django 5.0.7 on 2025-03-06 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_subject_standards'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['title'], 'verbose_name_plural': 'subjects'},
        ),
    ]
