# Generated by Django 5.0.7 on 2025-03-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timeslot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.SmallIntegerField()),
                ('end_time', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Timeslots',
                'ordering': ['start_time'],
                'unique_together': {('start_time', 'end_time')},
            },
        ),
    ]
