# Generated by Django 5.0.7 on 2025-03-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standard',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='standard',
            name='start_time',
        ),
        migrations.AddField(
            model_name='standard',
            name='title',
            field=models.SmallIntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
