# Generated by Django 5.0.7 on 2025-03-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_remove_standard_end_time_remove_standard_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standard',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
