# Generated by Django 5.0.7 on 2025-03-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0003_alter_standard_title'),
        ('subjects', '0004_remove_subject_standards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='teacher',
            new_name='class_teacher',
        ),
        migrations.AddField(
            model_name='standard',
            name='subjects',
            field=models.ManyToManyField(to='subjects.subject'),
        ),
    ]
